default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234

development:
  <<: *default
  database: airbnb_development

test:
  <<: *default
  database: airbnb_test

production:
  primary: &primary_production
    <<: *default
    database: airbnb_production
    username: airbnb
    password: <%= ENV["AIRBNB_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: airbnb_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: airbnb_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: airbnb_production_cable
    migrations_paths: db/cable_migrate
